// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/publishers',
        'getting-started/advertisers',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/best-practices',
        'guides/optimization',
        'guides/analytics',
      ],
    },
    {
      type: 'category',
      label: 'Technical Documentation',
      items: [
        'technical/api-reference',
        'technical/integration',
        'technical/security',
      ],
    },
    {
      type: 'category',
      label: 'Help & Support',
      items: [
        'help/troubleshooting',
        'help/support-tickets',
        'help/faq',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'API Reference',
    //   items: [
    //     'api/overview',
    //     'api/authentication',
    //     'api/endpoints',
    //     'api/webhooks',
    //   ],
    // },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        'faq/publishers',
        'faq/advertisers',
        'faq/general',
      ],
    },
  ],
};

export default sidebars;
